name: My First GitHub Action

on: 
  push:
    branches:
      - main

jobs: 
  say-hello:
    runs-on: self-hosted    # can switch to self-hosted/ubuntu-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print Hello World
        run: echo "Hello, GitHub Actions!"

