name: My Second GitHub Actions

on: [push]

jobs:
  build:
    runs-on: self-hosted    # can switch to self-hosted/ubuntu-hosted

  

    steps:
    - uses: actions/checkout@v3  
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x            # Use a specific version or define a matrix

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests
      run: |
        cd src
        python -m pytest addition.py
